export interface ImageType {
  id: string;
  class_id: string;
  resolution: string;
  url_mobile: string;
  url: string;
  url_thumb: string;
  url_mid: string;
  download_times: string;
  imgcut: string;
  tag: string;
  create_time: string;
  update_time: string;
  utag: string;
  tempdata: string;
  rdata: object[];
  img_1600_900: string;
  img_1440_900: string;
  img_1366_768: string;
  img_1280_800: string;
  img_1280_1024: string;
  img_1024_768: string;
}
